name: Execução de testes

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: '0 9,11,15,18 * * 1,2,3,4,5'

jobs:
  e2e-tests:
    runs-on: windows-latest

    steps:
      - name: Checkout do projeto
        uses: actions/checkout@v2

      - name: Configurar ambiente Java
        uses: actions/setup-java@v4
        with:
          java-version: '23.0.2'
          distribution: 'oracle'

      - name: Configurar Chrome Driver
        run: |
          choco install googlechrome
          curl -LO https://chromedriver.storage.googleapis.com/$(curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_win32.zip
          unzip chromedriver_win32.zip
          move chromedriver.exe C:\chromedriver

      - name: Executar testes
        run: mvn clean test

      - name: Gerar Relatório Allure
        run: mvn allure:report

      - name: Salvar allure-results como artefato
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results/

      - name: Salvar Relatório Allure como Artefato
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report/
