name: Execução de testes

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: '0 9,11,15,18 * * 1,2,3,4,5'

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: checkout projeto
        uses: actions/checkout@v2

      - name: Configurar ambiente Java
        uses: actions/setup-java@v4
        with:
          java-version: '23.0.2'
          distribution: 'oracle'

      - name: Configurar Chromer Driver
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          sudo apt-get install -y google-chrome-stable
          wget -q -O /tmp/chromedriver.zip https://chromedriver.storage.googleapis.com/$(curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_linux64.zip
          sudo unzip /tmp/chromedriver.zip -d /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver
        shell: bash


      - name: Instalar dependências com Maven
        run: mvn clean install

      - name: Executar testes
        run: mvn test


